# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4186b698935274823333861de5a8e885"
name = "tydal-clone"
handle = "tydal-clone"
application_url = "https://move-step-wt-er.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sharingan-plus.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://move-step-wt-er.trycloudflare.com/auth/callback",
  "https://move-step-wt-er.trycloudflare.com/auth/shopify/callback",
  "https://move-step-wt-er.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false
